// Seti RiverSide Resort - Admin Panel
// Firebase Authentication + Realtime Database

const DEFAULT_GALLERY = {
  image1:{url:'1.jpeg',title:'Discover Something Different',description:'Experience the natural beauty of our riverside setting.',order:1},
  image2:{url:'2.jpeg',title:'Refresh. Relax. Enjoy.',description:'Take a refreshing break surrounded by nature.',order:2},
  image3:{url:'3.jpeg',title:'Stay in Comfort',description:'Relax in comfortable rooms surrounded by greenery.',order:3}
};

window.addEventListener('DOMContentLoaded',()=>{
  if(!window.firebaseAuth){showLoginPage();showMessage('Firebase Authentication is not configured.','error');return;}
  firebaseAuth.onAuthStateChanged(user=>{
    if(!user){showLoginPage();return;}
    const allowed=Array.isArray(window.ADMIN_UIDS)?window.ADMIN_UIDS.filter(Boolean).filter(id=>!String(id).startsWith('YOUR_ADMIN_UID')):[]; if(allowed.length && !allowed.includes(user.uid)){firebaseAuth.signOut();showLoginPage();showMessage('This account is not authorized to access the admin panel.','error');return;}
    showAdminDashboard();loadGalleryGrid();loadDataFromFirebase();listenToReviews();
  });
});

function handleLogin(event){event.preventDefault();const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value,btn=document.getElementById('loginButton');if(!email||!password)return;btn.disabled=true;btn.textContent='Signing in...';firebaseAuth.signInWithEmailAndPassword(email,password).catch(error=>{let msg='Invalid email or password.';if(error.code==='auth/too-many-requests')msg='Too many attempts. Please try again later.';showMessage(msg,'error');document.getElementById('password').value='';}).finally(()=>{btn.disabled=false;btn.textContent='Login'});}
function handleLogout(){firebaseAuth.signOut();}
function showLoginPage(){document.getElementById('loginPage').style.display='flex';document.getElementById('adminDashboard').style.display='none';}
function showAdminDashboard(){document.getElementById('loginPage').style.display='none';document.getElementById('adminDashboard').style.display='flex';}
function switchTab(name,button){document.querySelectorAll('.tab-content').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));const tab=document.getElementById(name+'Tab');if(tab)tab.classList.add('active');if(button)button.classList.add('active');}

function loadGalleryGrid(){if(!window.firebaseDB)return;firebaseDB.ref('gallery').once('value').then(s=>renderAdminGallery(s.val()||{}));}
function renderAdminGallery(data){const merged={};new Set([...Object.keys(DEFAULT_GALLERY),...Object.keys(data||{})]).forEach(k=>merged[k]={...(DEFAULT_GALLERY[k]||{}),...(data&&data[k]||{})});const grid=document.getElementById('galleryGrid');grid.innerHTML='';const entries=Object.entries(merged).sort((a,b)=>(a[1]?.order??999999)-(b[1]?.order??999999));entries.forEach(([key,item])=>createGalleryEditor(key,item,grid));}
function createGalleryEditor(key,item,grid){const wrap=document.createElement('div');wrap.className='image-item gallery-admin-card';const src=item?.base64||item?.url||'';wrap.innerHTML=`<img src="${src}" alt="Gallery preview" id="preview-${key}"><div class="image-controls"><label>Image</label><input type="file" accept="image/*" onchange="uploadGalleryImage('${key}',this)"><input type="url" id="url-${key}" value="${escAttr(item?.url||'')}" placeholder="Or image URL"><label>Title</label><input type="text" id="title-${key}" value="${escAttr(item?.title||'')}" placeholder="Gallery title"><label>Description</label><textarea id="desc-${key}" rows="3" placeholder="Gallery description">${escText(item?.description||'')}</textarea><div class="admin-card-actions"><button class="save-btn" onclick="saveGalleryItem('${key}')">Save</button><button class="delete-btn" onclick="deleteGalleryItem('${key}')">Delete</button></div></div>`;grid.appendChild(wrap);}
function escAttr(v){return String(v).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function escText(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function uploadGalleryImage(key,input){const file=input.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=e=>{const preview=document.getElementById('preview-'+key);if(preview)preview.src=e.target.result;firebaseDB.ref('gallery/'+key).update({base64:e.target.result,url:'',timestamp:Date.now()}).then(()=>showMessage('Image uploaded. Save the title/description when ready.','success')).catch(err=>showMessage(err.message,'error'));};reader.readAsDataURL(file);}
function saveGalleryItem(key){const url=document.getElementById('url-'+key)?.value.trim()||'',title=document.getElementById('title-'+key)?.value.trim()||'',description=document.getElementById('desc-'+key)?.value.trim()||'';const preview=document.getElementById('preview-'+key);if(!preview?.src||(!url&&preview.src.endsWith('/'))){showMessage('Please provide an image first.','error');return}const payload={title,description,order:parseInt(String(key).replace(/\D/g,''),10)||999,timestamp:Date.now()};if(url)payload.url=url;firebaseDB.ref('gallery/'+key).update(payload).then(()=>{if(preview&&url)preview.src=url;showMessage('Gallery item saved.','success')}).catch(err=>showMessage(err.message,'error'));}
function addGalleryItem(){const keys=Object.keys({...DEFAULT_GALLERY,...(window._galleryCache||{})});let max=0;keys.forEach(k=>{const n=parseInt(String(k).replace(/\D/g,''),10);if(n>max)max=n});const key='image'+(max+1);window._galleryCache={...(window._galleryCache||{}),[key]:{title:'',description:'',order:max+1}};const grid=document.getElementById('galleryGrid');createGalleryEditor(key,window._galleryCache[key],grid);grid.lastElementChild.scrollIntoView({behavior:'smooth',block:'center'});}
function deleteGalleryItem(key){if(!confirm('Delete this gallery image?'))return;firebaseDB.ref('gallery/'+key).remove().then(()=>{document.getElementById('galleryGrid').querySelectorAll('.gallery-admin-card').forEach(card=>{if(card.querySelector('#preview-'+key))card.remove()});showMessage('Gallery image deleted.','success')}).catch(err=>showMessage(err.message,'error'));}

function saveContactInfo(){const data={phone:document.getElementById('phoneNumber').value.trim(),email:document.getElementById('emailAddress').value.trim(),address:document.getElementById('address').value.trim(),timestamp:Date.now()};firebaseDB.ref('contact-info').set(data).then(()=>showMessage('Contact information saved.','success')).catch(err=>showMessage(err.message,'error'));}
function saveSocialLinks(){const data={facebook:document.getElementById('facebookLink').value.trim(),instagram:document.getElementById('instagramLink').value.trim(),tiktok:document.getElementById('tiktokLink').value.trim(),timestamp:Date.now()};firebaseDB.ref('social-media').set(data).then(()=>showMessage('Social media links saved.','success')).catch(err=>showMessage(err.message,'error'));}
function loadDataFromFirebase(){firebaseDB.ref('contact-info').on('value',s=>{const d=s.val()||{};setVal('phoneNumber',d.phone);setVal('emailAddress',d.email);setVal('address',d.address)});firebaseDB.ref('social-media').on('value',s=>{const d=s.val()||{};setVal('facebookLink',d.facebook);setVal('instagramLink',d.instagram);setVal('tiktokLink',d.tiktok)});firebaseDB.ref('gallery').on('value',s=>{window._galleryCache=s.val()||{};renderAdminGallery(window._galleryCache)});}
function setVal(id,value){const el=document.getElementById(id);if(el&&value!==undefined)el.value=value||'';}
function listenToReviews(){firebaseDB.ref('reviews').on('value',s=>{const data=s.val()||{};const box=document.getElementById('adminReviewsList');const items=Object.entries(data).map(([id,v])=>({id,...v})).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));if(!items.length){box.innerHTML='<p>No guest reviews yet.</p>';return}box.innerHTML=items.map(v=>`<article class="admin-review-card"><div class="review-head"><strong>${escText(v.name||'Guest')}</strong><span class="admin-stars">${'★'.repeat(Number(v.rating)||5)}</span></div><p>${escText(v.review||'')}</p><small>${escText(v.email||'')} ${v.createdAt?'• '+new Date(v.createdAt).toLocaleString():''}</small><button class="delete-btn" onclick="deleteReview('${v.id}')">Delete Review</button></article>`).join('')})}
function deleteReview(id){if(!confirm('Delete this review permanently?'))return;firebaseDB.ref('reviews/'+id).remove().then(()=>showMessage('Review deleted.','success')).catch(err=>showMessage(err.message,'error'));}
function showMessage(message,type='success'){const div=document.createElement('div');div.className='success-message';div.textContent=message;if(type==='error')div.style.background='#f44336';document.body.appendChild(div);setTimeout(()=>div.remove(),3000);}
